{% set xfel_conda_channel = os.environ.get('XFEL_CONDA_CHANNEL', 'exflserv05.desy.de') %}
name: karabo-native

channels:
  - http://{{ xfel_conda_channel }}/karabo/channel
  - conda-forge
  - defaults

dependencies:
  - python=3.6.7=he025d50_1005 # [win]
  - python=3.6.* # [linux]
  - python=3.6.7 # [osx]
  - traits=4.6.0
  - python-dateutil=2.8
  - lxml=4.4.1
  - flake8=3.3.0
  - nose=1.3.7
  - numpy=1.15
  - pint=0.7.2

environment:
  PYTHONPATH:
    - {{ root }}
