{% set xfel_conda_channel = os.environ.get('XFEL_CONDA_CHANNEL', 'exflserv05.desy.de') %}
{% set conda_local_channel = os.environ.get('CONDA_LOCAL_CHANNEL_ENV', '') %}
name: karabo-cpp

channels:
  - http://{{ xfel_conda_channel }}/karabo/channel
  - conda-forge
  - defaults
{{ conda_local_channel }}

dependencies:
  - gxx_linux-64  # [linux]
  - libstdcxx-ng  # [linux]
  - clangxx       # [osx]
  - cmake>3.12
  - make
  - setuptools-scm
  - cogapp
  - log4cpp=1.1.3=xfel
  - boost=1.66=xfel
  - openssl
  - openmqc
  - nss
  - hdf5=1.10.2
  - icu
  # - sip
  - nlohmann_json
  - libtiff
  - pugixml=1.2=xfel
  - cppunit
